export const RESET = "RESET";

export const SET_BUSINESS_IS_LOADING = "SET_BUSINESS_IS_LOADING";
export const SET_BUSINESS_DATA = "SET_BUSINESS_DATA";
export const SET_BUSINESS_ERROR = "SET_BUSINESS_ERROR";
export const SET_BUSINESS_SELECTED = "SET_BUSINESS_SELECTED";
